--- 
  apiVersion: binaryomen.org/v1alpha1
  kind: Druid
  metadata: 
    name: druid
  spec: 
    historicals-cold: 
      mountPath: /opt/druid/conf/druid/cluster/data/historical
      nodeType: historical
      port: 8088
      replicas: 1
      runtime.properties: |
          druid.service=druid/historical
          druid.server.http.numThreads=5
          druid.processing.buffer.sizeBytes=1
          druid.processing.numMergeBuffers=1
          druid.processing.numThreads=1
          # Segment storage
          druid.segmentCache.locations=[{\"path\":\"/druid/data/segments\",\"maxSize\":10737418240}]
          druid.server.maxSize=10737418240
      volumeClaimTemplates: 
        - 
          metadata: 
            name: data-volume
          spec: 
            accessModes: 
              - ReadWriteOnce
            resources: 
              requests: 
                storage: 1Gi
      volumeMounts: 
        - 
          mountPath: /druid/data
          name: data-volume
    historicals-hot: 
      mountPath: /opt/druid/conf/druid/cluster/data/historical
      nodeType: historical
      port: 8088
      replicas: 1
      runtime.properties: |
          druid.service=druid/historical
          druid.server.http.numThreads=5
          druid.processing.buffer.sizeBytes=1
          druid.processing.numMergeBuffers=1
          druid.processing.numThreads=1
          # Segment storage
          druid.segmentCache.locations=[{\"path\":\"/druid/data/segments\",\"maxSize\":10737418240}]
          druid.server.maxSize=10737418240
      volumeClaimTemplates: 
        - 
          metadata: 
            name: data-volume
          spec: 
            accessModes: 
              - ReadWriteOnce
            resources: 
              requests: 
                storage: 1Gi
      volumeMounts: 
        - 
          mountPath: /druid/data
          name: data-volume
    image: "apache/incubator-druid:0.16.0-incubating"
    startscript: /druid.sh
  
